[project]
name = "CarrotAI-PRC-AirPrice"
version = "0.1.0"
description = "PRC AirPrice MCP Server"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp>=1.9.0",
    "requests>=2.32.3",
]
